### ISSUE TITLE
got $$hashKey of undefined error when works with ui-leaflet 1.0.2

### ISSUE THREAD

**Issue by ulion** [elesdoar/ui-leaflet-layers#2]
while ui-leaflet 1.0.1 works well.

**Comment by ulion** [comment]
well, it seems mainly caused by layerTypes is not exposed in newer ui-leaflet, but in master branch.

**Comment by elesdoar** [comment]
Please use with ui-leaflet 2.0.0 or later, version 1.x don't implement decorators for plugins.
