### ISSUE TITLE
Plugin not working when ng-strict-di is set to true

### ISSUE THREAD

**Issue by slavede** [elesdoar/ui-leaflet-layers#3]
In case you include ng-strict-di="true" inside your html tag, AngularJS will throw an error:

```

angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module MonicaApp due to:
Error: [$injector:modulerr] Failed to instantiate module ui-leaflet due to:
Error: [$injector:strictdi] function($provide) is not using explicit annotation and cannot be invoked in strict mode
http://errors.angularjs.org/1.5.5/$injector/strictdi?p0=function(%24provide)
```

The solution is to write a proper dependency injection.

i.e., not:

`function($provide) {...}`

but

`['$provide', function($provide) {...}`

**Comment by nmccready** [comment]
Sounds like a pretty easy problem to find and fix. PR's are welcomed.

**Comment by slavede** [comment]
Yeah, I can do it, I just wanted to see if you agree. Thanks, I'll fix it these days and create PR

**Comment by nmccready** [comment]
I assume this is a problem on master? If not then make the PR against 1.X , then  it can be rolled into both. I haven't searched for the issue yet, but yes if the annotation is missing it is a minify error for sure.
